"""The examples are documentation, so their first-run behaviour is a contract.

``examples/sample_data/`` is gitignored and generated by
``00_setup/generate_sample_data.py``. ``examples/README.md`` promises that every
other script "fails with an actionable message if you skip it", and
``_common.require_sample_data`` exists to deliver exactly that. Nothing held the
README to that promise, and F-9.1 found the gap in the worst possible place: the
one script the README tells you to run first.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
SAMPLE = REPO / "examples" / "sample_data"
# 00_setup is excluded: it *creates* the data, so it must run without it.
SCRIPTS = sorted(p for p in (REPO / "examples").glob("0*/*.py")
                 if p.parent.name != "00_setup")


@pytest.fixture
def without_sample_data(tmp_path):
    """Hide examples/sample_data for one test, restoring it unconditionally."""
    if not SAMPLE.exists():
        yield                      # already absent; nothing to hide or restore
        return
    stashed = tmp_path / "sample_data"
    SAMPLE.rename(stashed)
    try:
        yield
    finally:
        if not SAMPLE.exists():
            stashed.rename(SAMPLE)


@pytest.mark.parametrize("script", SCRIPTS,
                         ids=lambda p: f"{p.parent.name}/{p.stem}")
def test_example_explains_missing_sample_data(script, without_sample_data):
    """No example may greet a new user with a bare FileNotFoundError."""
    proc = subprocess.run([sys.executable, str(script)],
                          capture_output=True, text=True, cwd=str(REPO))
    out = proc.stdout + proc.stderr
    assert proc.returncode != 0, f"{script.name} succeeded without sample data"
    assert "FileNotFoundError" not in out, (
        f"{script.name} raised a bare FileNotFoundError instead of an "
        f"actionable message:\n...{out[-300:]}")
    assert "generate_sample_data" in out, (
        f"{script.name} did not name the generator:\n...{out[-300:]}")
